spring.application.name=SimpleCacheApplication

spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=Siva@72880
spring.jpa.hibernate.ddl-auto=update


